//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Centralite.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASNEntry
    {
        public int id { get; set; }
        public int euiId { get; set; }
        public int serialNumberId { get; set; }
        public string shipper { get; set; }
        public System.DateTime date { get; set; }
    
        public virtual EuiList EuiList { get; set; }
        public virtual SerialNumber SerialNumber { get; set; }
    }
}
