//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Centralite.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class BoardRevision
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BoardRevision()
        {
            this.TestSessions = new HashSet<TestSession>();
        }
    
        public int Id { get; set; }
        public int Revision { get; set; }
        public string MfgTokens { get; set; }
        public bool HasPA { get; set; }
        public int BoardId { get; set; }
        public int EEPROMId { get; set; }
        public bool Release { get; set; }
        public bool BoostMode { get; set; }
        public bool ExternalPAAlt { get; set; }
        public bool ExternalPABidirectional { get; set; }
        public byte BoostTXPower { get; set; }
        public bool ALT_TX { get; set; }
        public bool ALT_RX { get; set; }
        public Nullable<int> ChipSelect { get; set; }
        public string Port { get; set; }
        public bool FlashTest { get; set; }
        public Nullable<int> BOMRevision { get; set; }
    
        public virtual Board Board { get; set; }
        public virtual EEPROM EEPROM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TestSession> TestSessions { get; set; }
    }
}
