//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Centralite.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bootloader
    {
        public int Id { get; set; }
        public Nullable<int> EEPROMId { get; set; }
        public int ChipTypeId { get; set; }
        public int Version { get; set; }
        public string Owner { get; set; }
        public byte[] Data { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual ChipType ChipType { get; set; }
        public virtual EEPROM EEPROM { get; set; }
    }
}
