//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Centralite.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeletedDevice
    {
        public int Id { get; set; }
        public int TesterId { get; set; }
        public Nullable<int> EuiId { get; set; }
        public int ProductId { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual EuiList EuiList { get; set; }
        public virtual Product Product { get; set; }
        public virtual Tester Tester { get; set; }
    }
}
