//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Centralite.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoryRemoteTestResult
    {
        public int Id { get; set; }
        public string TestDeviceEui { get; set; }
        public bool TestPassed { get; set; }
        public System.DateTime TestDate { get; set; }
        public int UserSessionId { get; set; }
    }
}
