//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Centralite.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class GarageDoorControllerTest
    {
        public int id { get; set; }
        public int EuiId { get; set; }
        public int NetworkColorId { get; set; }
        public int UserSessionId { get; set; }
        public bool SensorPaired { get; set; }
        public bool LoadOn { get; set; }
        public bool LoadOff { get; set; }
        public bool MotionSensor { get; set; }
        public bool SelfTestMode { get; set; }
        public bool ButtonDetected { get; set; }
        public bool DeviceDefaulted { get; set; }
        public string Error { get; set; }
        public System.DateTime TestDate { get; set; }
        public bool UnoccupiedStatus { get; set; }
    
        public virtual EuiList EuiList { get; set; }
        public virtual NetworkColor NetworkColor { get; set; }
        public virtual UserSession UserSession { get; set; }
    }
}
