//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Centralite.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class JabilErrorView
    {
        public int EuiId { get; set; }
        public string Eui { get; set; }
        public System.DateTime StartTime { get; set; }
        public string TestType { get; set; }
        public string Error { get; set; }
        public string Isa { get; set; }
        public string Tester { get; set; }
    }
}
