//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Centralite.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class LabelView
    {
        public int SerialNumber { get; set; }
        public string EUI { get; set; }
        public int ProductionSiteId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int TesterId { get; set; }
        public int FirmwareId { get; set; }
        public int ProductId { get; set; }
    }
}
