//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Centralite.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class NetworkColor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NetworkColor()
        {
            this.GarageDoorControllerTests = new HashSet<GarageDoorControllerTest>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int Channel { get; set; }
        public int Pan { get; set; }
        public string ExtendedPan { get; set; }
        public string SerialMapping { get; set; }
        public string Host { get; set; }
        public int Port { get; set; }
        public Nullable<int> ForcedChannel { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GarageDoorControllerTest> GarageDoorControllerTests { get; set; }
    }
}
