//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Centralite.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class PowerTest
    {
        public int Id { get; set; }
        public int EuiId { get; set; }
        public int UserSessionId { get; set; }
        public double PowerValue { get; set; }
        public double ReferenceValue { get; set; }
        public double Deviation { get; set; }
        public double AllowedDeviation { get; set; }
    
        public virtual EuiList EuiList { get; set; }
        public virtual UserSession UserSession { get; set; }
    }
}
