//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Centralite.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.DeletedDevices = new HashSet<DeletedDevice>();
            this.ProductionSiteProductJoins = new HashSet<ProductionSiteProductJoin>();
            this.SerialNumbers = new HashSet<SerialNumber>();
            this.TestSessions = new HashSet<TestSession>();
            this.Firmwares = new HashSet<Firmware>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string ModelString { get; set; }
        public string Description { get; set; }
        public Nullable<bool> Released { get; set; }
        public int BoardId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string SerialNumberCode { get; set; }
        public string ZigbeeModelString { get; set; }
        public int ExtensionId { get; set; }
        public string SKU { get; set; }
        public bool CurrentTest { get; set; }
        public Nullable<int> ModelEncodingNumber { get; set; }
        public string ZplFile { get; set; }
        public bool EnableReadProtectOnDevice { get; set; }
        public string BoxLabelName { get; set; }
    
        public virtual Board Board { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeletedDevice> DeletedDevices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductionSiteProductJoin> ProductionSiteProductJoins { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SerialNumber> SerialNumbers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TestSession> TestSessions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Firmware> Firmwares { get; set; }
    }
}
