//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Centralite.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class RangeTestSetting
    {
        public int RequiredValidSamples { get; set; }
        public int MaxAttempts { get; set; }
        public double FailureThreshold { get; set; }
        public int TxLqiThreshold { get; set; }
        public int TxRssiThreshold { get; set; }
        public int RxLqiThreshold { get; set; }
        public int RxRssiThreshold { get; set; }
        public int Id { get; set; }
        public string TestStationMac { get; set; }
        public string RangeTestMasterIp { get; set; }
        public int RangeTestMasterPort { get; set; }
    }
}
