//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Centralite.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class RangeTestFirmware
    {
        public int Id { get; set; }
        public string FirmwareVersion { get; set; }
        public byte[] Data { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int ChipTypeId { get; set; }
    
        public virtual ChipType ChipType { get; set; }
    }
}
