//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Centralite.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class SerialChange
    {
        public int Id { get; set; }
        public string Eui { get; set; }
        public string OldSerial { get; set; }
        public string NewSerial { get; set; }
        public int OldTesterId { get; set; }
        public int NewTesterId { get; set; }
        public int SupervisorId { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Supervisor Supervisor { get; set; }
        public virtual Tester Tester { get; set; }
        public virtual Tester Tester1 { get; set; }
    }
}
