//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Centralite.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class TargetDevice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TargetDevice()
        {
            this.Tests = new HashSet<Test>();
        }
    
        public int Id { get; set; }
        public int IsaId { get; set; }
        public Nullable<int> EuiId { get; set; }
        public int TestSessionId { get; set; }
        public int ResultId { get; set; }
    
        public virtual EuiList EuiList { get; set; }
        public virtual InsightAdapter InsightAdapter { get; set; }
        public virtual Result Result { get; set; }
        public virtual TestSession TestSession { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Test> Tests { get; set; }
    }
}
