//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Centralite.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestSession
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TestSession()
        {
            this.TargetDevices = new HashSet<TargetDevice>();
        }
    
        public int Id { get; set; }
        public int ProductId { get; set; }
        public int BoardRevisionId { get; set; }
        public int FirmwareId { get; set; }
        public int UserSessionId { get; set; }
        public int ResultId { get; set; }
        public System.DateTime StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
    
        public virtual BoardRevision BoardRevision { get; set; }
        public virtual Firmware Firmware { get; set; }
        public virtual Product Product { get; set; }
        public virtual Result Result { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TargetDevice> TargetDevices { get; set; }
        public virtual UserSession UserSession { get; set; }
    }
}
